# Default language if you have a multi-language setup
DefaultContentLanguage = "en"

baseURL = "https://saastips.xyz/"

theme = "mytheme"
name= "SaasTips"

pygmentsUseClasses = true

# Number of posts shown per page (dafault: 10)
paginate = 3

# Language sections
[languages]
    [languages.en]
        contentDir = "content"
        languageName = "English"
        languageCode = "en"
        title = "Amperage theme!"
        description = "This is an demo for the Amperage theme!"
        weight = 1
# Menu elements
[[menu.main]]
    identifier = "saastips"
    name = "SaasTips"
    weight = 8


[params]
    copyright = "SaasTips" # Name shown on footer copyright
    themeColor = "#333" # Theme color displayed on mobile browsers

    # Default AMP components for the whole site
    ampElements = ["amp-iframe", "amp-analytics", "amp-social-share", "amp-install-serviceworker"]

    # Google Analytics code
    # googleAnalytics = "UA-xxxxxxxxx-x"

    # Adsense publisher code
    # adsensePublisher = "ca-pub-123456789"

    # Comments Iframe URL
    # commentsEmbedUrl = "https://comments.example.com"

    # Social sites for metatags
    facebookSite = "example"
    twitterSite = "@example"

    # Structured data elements
    socialProfiles = ["https://twitter.com/example","https://www.linkedin.com/in/example/","https://github.com/example"]

    alternatePageName = "Amperage example"
    organizationLogo = "/logo.png"
    organizationName = "Asur"

    publisherName = "amperage"
    publisherLogo = "/logo-amp-article.png"
    publisherLogoWidth = 600
    publisherLogoHeight = 60

[markup]
    defaultMarkdownHandler = "blackfriday"